channels:
- conda-forge
- nodefaults
dependencies:
- attrs
- cfgrib
- ecmwf-datastores-client
- ecmwf-opendata
- jsonschema
- make
- mypy
- myst-parser
- pandas-stubs
- pip
- pre-commit
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinx-autoapi
- xarray
- pip:
  - polytope-client
